In [2]:
#bài 1
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)
print("kích thước là: 2x3")
print("số chiều là:" , a.ndim)
print("kiểu dữ liệu là: int 32bit: ", a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
kích thước là: 2x3
số chiều là: 2
kiểu dữ liệu là: int 32bit:  torch.int32


In [ ]:
# bài 2
a = torch.rand(3,4)
b = torch.randn(3,4)
c = torch.zeros(2,3)
d = torch.ones(2,3)
e = torch.eye(4)
ans = torch.zeros(5,5)
print(a)
print(b)
print(c)
print(d)
print(e)
print("Sự khác nhau giữa torch.rand() và torch.randn(): rand không có số âm nhưng randn lại có")
print(ans)

tensor([[0.0960, 0.2816, 0.2035, 0.0919],
        [0.3930, 0.8391, 0.8018, 0.9806],
        [0.1327, 0.1452, 0.2015, 0.4654]])
tensor([[-1.8576, -0.7751, -0.2476,  1.2855],
        [ 0.6508, -2.5522,  0.6049, -1.1949],
        [-1.3029, -1.2643, -1.3608, -0.1843]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Sự khác nhau giữa torch.rand() và torch.randn(): rand không có số âm nhưng randn lại có
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
# bài 3
a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)
print("ý nghĩa của torch.Size([2, 3, 4]) là: tạo ra ma trận 3 chiều 2x3x4")

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32
ý nghĩa của torch.Size([2, 3, 4]) là: tạo ra ma trận 3 chiều 2x3x4


In [6]:
# bài 4
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])
print("shape của a[1]: ", a[1].shape)
print("shape của a[1:, 2:4]: ", a[1:, 2:4].shape)
print(a[..., -2:])

Original tensor:
tensor([[[ 0.8560, -2.3519,  0.4790,  1.2041,  1.0407],
         [ 0.5878,  1.3281,  0.9783,  0.2651, -0.0121],
         [-0.2228, -1.5272, -0.3422, -1.2026, -0.8965],
         [-0.0770, -0.7758,  1.4267, -0.4100,  0.9892]],

        [[ 0.7944, -0.6346, -0.7571, -0.6985,  0.3425],
         [-1.7650, -0.2971,  1.3887, -1.2424, -0.2862],
         [ 0.7324,  0.5818,  1.1053,  2.0331,  0.0482],
         [ 1.1344,  0.2326,  1.9083,  0.1060, -1.5574]],

        [[-0.5870, -1.6730, -1.0666,  0.7374, -0.3688],
         [-0.6094,  0.3552, -1.7742,  1.2813, -0.5407],
         [-0.7877,  0.4177, -0.0551,  0.0194,  0.5276],
         [ 0.3694,  0.0531, -1.0335, -0.4586,  0.2609]]])

Tensor a[1]:
tensor([[ 0.7944, -0.6346, -0.7571, -0.6985,  0.3425],
        [-1.7650, -0.2971,  1.3887, -1.2424, -0.2862],
        [ 0.7324,  0.5818,  1.1053,  2.0331,  0.0482],
        [ 1.1344,  0.2326,  1.9083,  0.1060, -1.5574]])

Tensor a[1:, 2:4]:
tensor([[[ 0.7324,  0.5818,  1.1053,  2.0331,  0.0

In [ ]:
# bài 5
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

print("\nReshape to 2x6:")
print(a.reshape(2,6))
print("số phần tử trước và sau khi reshape la: 12")

Original:
tensor([[ 0.3826,  0.9880, -0.8057,  1.8290],
        [ 0.6102, -0.7129, -0.3013, -1.7806],
        [-1.2407, -0.3054,  0.2429,  2.1120]])

Flatten:
tensor([ 0.3826,  0.9880, -0.8057,  1.8290,  0.6102, -0.7129, -0.3013, -1.7806,
        -1.2407, -0.3054,  0.2429,  2.1120])

Reshape to 3 x 2 x 2:
tensor([[[ 0.3826,  0.9880],
         [-0.8057,  1.8290]],

        [[ 0.6102, -0.7129],
         [-0.3013, -1.7806]],

        [[-1.2407, -0.3054],
         [ 0.2429,  2.1120]]])

Reshape to 2x6:
tensor([[ 0.3826,  0.9880, -0.8057,  1.8290,  0.6102, -0.7129],
        [-0.3013, -1.7806, -1.2407, -0.3054,  0.2429,  2.1120]])
số phần tử trước và sau khi reshape la: 12


In [ ]:
# bài 6
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)
c=a @ b.T
print('phép toán a * b với a @ b.T: a*b là nhân từng phần tử, a@b.T là nhân ma trận a với ma trận chuyển vị b, phải chuyển vị vì cột ma trận này phải bằng hàng ma trận kia')
print(c.shape)

a:
tensor([[ 0.2794,  0.5958, -1.4230],
        [ 1.2068,  0.8206, -0.6213]])
b:
tensor([[ 1.2515,  2.7432, -1.2687],
        [-1.4367,  0.0876,  1.1181]])

a + b:
tensor([[ 1.5309,  3.3390, -2.6917],
        [-0.2299,  0.9082,  0.4969]])

a / b:
tensor([[ 0.2233,  0.2172,  1.1216],
        [-0.8400,  9.3675, -0.5556]])

a^2:
tensor([[0.0781, 0.3550, 2.0250],
        [1.4564, 0.6733, 0.3860]])

Matrix multiplication:
tensor([[ 3.7895, -1.9404],
        [ 4.5495, -2.3567]])
phép toán a * b với a @ b.T: a*b là nhân từng phần tử, a@b.T là nhân ma trận a với ma trận chuyển vị b, phải chuyển vị vì cột ma trận này phải bằng hàng ma trận kia
torch.Size([2, 2])


In [ ]:
# bài 7
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))
print(torch.cumsum(a, dim=1))

print("dim 0 là cột còn dim 1 là dòng")

tensor([[-1.0737,  0.9198,  0.6363, -0.0976],
        [ 0.2388,  0.7803, -2.0800,  0.5047],
        [ 0.0827, -0.3991,  0.1416, -0.2506]])

Mean:
tensor([-0.2507,  0.4337, -0.4340,  0.0522])
tensor([ 0.0962, -0.1391, -0.1064])

Standard deviation:
tensor([0.7170, 0.7246, 1.4468, 0.3993])
tensor([0.8900, 1.3127, 0.2606])

Cumulative sum:
tensor([[-1.0737,  0.9198,  0.6363, -0.0976],
        [-0.8349,  1.7001, -1.4437,  0.4071],
        [-0.7522,  1.3010, -1.3021,  0.1565]])
tensor([[-1.0737, -0.1538,  0.4824,  0.3849],
        [ 0.2388,  1.0191, -1.0610, -0.5562],
        [ 0.0827, -0.3164, -0.1748, -0.4254]])
dim 0 là cột còn dim 1 là dòng


In [7]:
# bài 8
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)
print("đạo hàm y=x^2: ", 2 * 3.6)

x.grad.zero_()
y2 = 3*x**2 + 2*x + 1
y2.backward()
print("y2 =", y2)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)
đạo hàm y=x^2:  7.2
y2 = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


In [ ]:
# bài 9
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
  optimizer.zero_grad()
  y_pred = x @ w
  mse = torch.mean(torch.square(y - y_pred))
  mse.backward()
  optimizer.step()
print("Learned coefficients:")
print(w)

print("hệ số học gàn bằng các với [1,2,3]")
print("optimizer.zero_grad() là xóa grad cũ để không bị công dồn")
print("mse.backward() thì sẽ tính gradient của MSE theo w (dmse/dw)")
print("optimizer.step() là dùng gradient để cập nhật trọng số (w←w−lr⋅gradient)")

Initial coefficients:
tensor([[ 0.0631],
        [-0.4011],
        [ 0.1981]], requires_grad=True)
Learned coefficients:
tensor([[1.0083],
        [2.0575],
        [2.5070]], requires_grad=True)
hệ số học gàn bằng các với [1,2,3]
optimizer.zero_grad() là xóa grad cũ để không bị công dồn
mse.backward() thì sẽ tính gradient của MSE theo w (dmse/dw)
optimizer.step() là dùng gradient để cập nhật trọng số (w←w−lr⋅gradient)


In [ ]:
# bài 10
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
  y1 = A + B - 9
  y2 = C - D - 1
  y3 = A + C - 8
  y4 = B - D - 2
  sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
  optimizer.zero_grad()
  sqerr.backward()
  optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

print(A + B, "= 9")
print(C - D, "= 1")
print(A + C, "= 8")
print(B - D, "= 2")

print("bài toán có thể có nhiều nghiệm vì ngay từ đề bài của bài toán các phương trình đã làm cho A B C D có nhiều nghiệm")

A = tensor(4.4287, requires_grad=True)
B = tensor(4.5713, requires_grad=True)
C = tensor(3.5713, requires_grad=True)
D = tensor(2.5713, requires_grad=True)
tensor(9.0000, grad_fn=<AddBackward0>) = 9
tensor(1.0000, grad_fn=<SubBackward0>) = 1
tensor(8.0000, grad_fn=<AddBackward0>) = 8
tensor(2.0000, grad_fn=<SubBackward0>) = 2
bài toán có thể có nhiều nghiệm vì ngay từ đề bài của bài toán các phương trình đã làm cho A B C D có nhiều nghiệm


In [ ]:
# bài 11
import random
import numpy as np
import torch
a = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24], dtype=torch.int32)
print(a)
print(a.reshape(4,6))
print(a.reshape(2,12))
print(a.reshape(2,3,4))

A = torch.randn(3,4)
B = torch.randn(3,4)
print(A + B)
print(A * B)
print(A / B)
print(torch.mean(A,dim=0))
print(torch.std(A,dim=0))

x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5*x + 3
y.backward()
print("=====================================")
print("y = ",y.item())
print("x = ",x.grad.item())
print("dy/dx = 4x + 5, 4x2+5 = 13")
print("=====================================")

polynomial = np.poly1d([2, -3, 5])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
  optimizer.zero_grad()
  y_pred = x @ w
  mse = torch.mean(torch.square(y - y_pred))
  mse.backward()
  optimizer.step()
print("Learned coefficients:")
print(w)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24], dtype=torch.int32)
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=torch.int32)
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=torch.int32)
tensor([[-0.8748, -0.5380,  0.7706, -0.6719],
        [ 0.7871,  1.6840,  0.0521,  0.8532],
        [-0.3772, -1.8499, -0.4864, -0.9319]])
tensor([[-0.1182, -0.5961,  0.0855,  0.1009],
        [-0.0740,  0.6627, -0.1899, -0.4584],
        [-0.4640,  0.3530,  0.0311, -0.0516]])
tensor([[ -8.3530,  -1.9807,   0.2113,   0.5096],
        [-10.2806,   0.5932,  -1.1270,  -0.3046],
        [ -1.